# Generated by Django 4.2.4 on 2023-08-08 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaleList', '0008_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
