# Generated by Django 4.2.4 on 2023-08-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleList', '0013_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FF', '신선식품'), ('PF', '가공식품'), ('DN', '생활용품')], max_length=50),
        ),
    ]
