# Generated by Django 4.2.4 on 2023-08-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaleList', '0015_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_uploaded',
            field=models.DateField(auto_now=True),
        ),
    ]
