# Generated by Django 4.2.4 on 2023-08-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcode_images/'),
        ),
    ]
