# Generated by Django 4.2.4 on 2023-08-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_barcode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='barcode_uploaded',
            field=models.DateField(auto_now=True),
        ),
    ]
