# Generated by Django 4.2.4 on 2023-08-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_product_code', models.CharField(max_length=10)),
                ('limit_product_name', models.CharField(max_length=100)),
                ('limit_stock', models.PositiveIntegerField()),
                ('limit_regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limit_discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limit_product_image', models.ImageField(upload_to='limit_product_images/')),
            ],
        ),
    ]
