# Generated by Django 4.2.4 on 2023-08-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LimitList', '0002_alter_limitproduct_limit_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitproduct',
            name='limit_uploaded',
            field=models.DateField(auto_now=True),
        ),
    ]
