# Generated by Django 4.2.4 on 2023-08-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LimitList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reservation_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LimitList.limitproduct')),
            ],
        ),
    ]
